# NUMPY

## Numpy is a general puprose array-processing package in python

In [1]:
import numpy as np

In [2]:
#1d array from a python list
arr1d = np.array([1,2,3,4,5])
#2d array from a nested python list
arr2d = np.array([[1,2,3],[4,5,6]])

In [3]:
zeros_arr = np.zeros((3,4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Array attributes

In [4]:
#shape
shape = arr2d.shape
print(shape)

(2, 3)


In [5]:
#size
size = arr2d.size
print(size)

6


In [6]:
#data type
data_type = arr2d.dtype
print(data_type)

int32


## Array Operations

In [7]:
#addition
addition = 2 + arr2d
print(addition)

[[3 4 5]
 [6 7 8]]


In [8]:
#subtraction
subtraction = arr2d - 3
print(subtraction)

[[-2 -1  0]
 [ 1  2  3]]


In [9]:
#Multiplication
multiplication = 4 * arr2d
print(multiplication)

[[ 4  8 12]
 [16 20 24]]


## Aggregation Functions

In [10]:
#sum
total_sum = arr2d.sum()
print(total_sum)

21


In [11]:
#max
max_val = arr2d.max()
print(max_val)

6


In [12]:
#min
min_val = arr2d.min()
print(min_val)

1


## Indexing

In [13]:
#second row
second_row = arr2d[1:,:]
print(second_row)

[[4 5 6]]


In [14]:
#first row
first_row = arr2d[0:1,:]
print(first_row)

[[1 2 3]]


In [15]:

second_row_element = arr2d[1:,1:]
print(second_row_element)

[[5 6]]


In [16]:
first_row_element = arr2d[0:1,0:2]
print(first_row_element)

[[1 2]]


In [17]:
first_row_ = arr2d[0:1,1:]
print(first_row_)

[[2 3]]


In [18]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [19]:
first_row_ = arr2d[0,1:]
print(first_row_)

[2 3]


In [20]:
first_row_ = arr2d[:1,1:]
print(first_row_)

[[2 3]]


In [21]:
first_row_ = arr2d[0,1:]
print(first_row_)

[2 3]


## Array Manipulation

In [22]:
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [23]:
#reshape
reshaped_arr = arr2d.reshape(3,2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
reshaped_arr1 = arr2d.reshape(1,6)
print(reshaped_arr1)

[[1 2 3 4 5 6]]


In [25]:
#Concatenate Arrays
arr1d = [1,2,3]
concat_arr = np.concatenate([arr1d,arr1d])
print(concat_arr)

[1 2 3 1 2 3]


In [26]:
#Concatenate Arrays 2
arr1d = np.array([1,2,3])
concat_arr2 = np.concatenate([arr1d,np.array([4,5,6])])
print(concat_arr2)

[1 2 3 4 5 6]


In [27]:
#append
arr1d = np.array([1,2,3])
append_arr = np.append(arr1d,[4,5,6])
print(append_arr)

[1 2 3 4 5 6]


In [28]:
#append to 2 dimensional array
arr2d = np.array([[1,2,3],[4,5,6]])
append_arr1 = np.append(arr2d,[7,8,9])
print(append_arr1)

[1 2 3 4 5 6 7 8 9]


## Question asked

### Can you append a row ([4,5,6]) to the array [1,2,3], so it looks like this [[1,2,3],[4,5,6]] rather than this: [1,2,3,4,5,6]?

### Answer: To achieve that, both arrays need to be two-dimensional arrays.

In [30]:
#Answer to question asked
arr1d = np.array([[1,2,3]])
concat_arr2 = np.concatenate([arr1d,np.array([[4,5,6]])])
print(concat_arr2)

[[1 2 3]
 [4 5 6]]


## Broadcasting

In [31]:
#broadcasting
a = np.array([1,2,3])
b = 4
print(a+b)

[5 6 7]


In [32]:
a = np.array([1,2,3])
b = 6
print(a*b)

[ 6 12 18]


In [33]:
a = np.array([1,2,3])
print(4 + a)

[5 6 7]


## Random Number Generation

In [34]:
random_numbers = np.random.rand(3,3)
print(random_numbers)

[[0.96468241 0.17797779 0.68136972]
 [0.81117361 0.85460381 0.53754127]
 [0.12628214 0.38699588 0.18485111]]


In [35]:
random_numbers = np.random.rand(4,6)
print(random_numbers)

[[0.13982472 0.9226211  0.75043573 0.07342444 0.41681985 0.66383607]
 [0.55283402 0.20124802 0.7336953  0.64163205 0.86002604 0.83301745]
 [0.1295206  0.40016586 0.93971919 0.93043012 0.41874235 0.82674411]
 [0.5942855  0.65743556 0.55425314 0.94627769 0.38718068 0.03927191]]


In [36]:
random_numbers_ = np.random.randint(0,100,6)
print(random_numbers_)

[93 20 81 13 16 84]


In [37]:
random_numbers_ = np.random.randint(0,100,6).reshape(3,2)
print(random_numbers_)

[[77 47]
 [82 67]
 [82 88]]


## Linear Algebra

In [38]:
# Matrix Addition
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A + B)

[[ 6  8]
 [10 12]]


In [39]:
#Matrix Subtraction
print(A - B)

[[-4 -4]
 [-4 -4]]


In [40]:
#Matrix Multiplication
print(A * B)

[[ 5 12]
 [21 32]]


In [41]:
#Normal Matrix Multiplication
F = np.dot(A,B)
print(F)

[[19 22]
 [43 50]]


In [42]:
#Matrix Multiplication (Column-wise)
print(A * B)

[[ 5 12]
 [21 32]]


In [44]:
# Standard Matrix multiplication
F = np.dot(A,B)
print(F)

[[19 22]
 [43 50]]


In [45]:
#Transpose of a matrix
transpose_A = np.transpose(A)
print(transpose_A)

[[1 3]
 [2 4]]


In [46]:
#Transpose of a matrix
transpose_B = np.transpose(B)
print(transpose_B)

[[5 7]
 [6 8]]


In [47]:
#Inverse of a matrix
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [48]:
#Inverse of a matrix
B_inv = np.linalg.inv(B)
print(B_inv)

[[-4.   3. ]
 [ 3.5 -2.5]]


In [49]:
#identity Matrix
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [50]:
#determinant of a matrix
determinant = np.linalg.det(B)
print(int(determinant))

-2


## Delete elements in an array

In [51]:
arr = np.array([1,2,3,4,5])
arr_deleted = np.delete(arr,2)
print(arr_deleted)

[1 2 4 5]


In [52]:
arr_deleted = np.delete(arr,4)
print(arr_deleted)

[1 2 3 4]


In [53]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
print(arr_deleted)

['Madrid' 'Dortmund' 'PSG' 'Mancity']


In [54]:
arr = np.array([1,2,3,4,5])
m = arr != 5
new_arr = arr[m]
print(new_arr)

[1 2 3 4]


### To make sure that the elements that are removed in arr_deleted are also deleted in club_arr

In [56]:
club_arr = np.array(['Madrid','Barcelona','Arsenal','Dortmund','PSG','Mancity'])
arr_deleted = np.delete(club_arr,[1,2])
club_arr = arr_deleted
print(club_arr)
      

['Madrid' 'Dortmund' 'PSG' 'Mancity']


## Statistical Functions

In [57]:
arr = np.array([1,2,3,4,5])


In [58]:
#mean
arr_mean = np.mean(arr)
print(arr_mean)

3.0


In [59]:
#median
arr_median = np.median(arr)
print(arr_median)

3.0


In [61]:
#Mode : numpy does not have the mode method, so scipy can be used
arr_ = np.array([1,2,2,3,4,5,6])
from scipy import stats
arr_mode = stats.mode(arr_,keepdims = False)
print(arr_mode)

ModeResult(mode=2, count=2)


In [62]:
#standard deviation
arr_std = np.std(arr)
print(arr_std)

1.4142135623730951
